Repository Apex-Innovations-LK/Healthcare-Appointment-and-Management-System, pull requests merged in 2025-05, with the labels that each got.

#28 dockerized the frontend
  client/.dockerignore
  client/Dockerfile
  client/README.md
Labels: docker

#30 Refactor IPFS service: Update HealthRecord and HealthRecordHashed DTO…
  server/health-record-service/src/main/resources/application.properties
  server/ipfs-service/docker-compose.yml
  server/ipfs-service/src/main/java/com/team07/ipfs_service/config/KafkaConfig.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/constants/KafkaTopics.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/controllers/IPFSController.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/dto/HealthRecord.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/dto/HealthRecordHashed.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/ipfs/FileServiceImpl.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/ipfs/IPFSService.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/producer/IPFSProducer.java
  server/ipfs-service/src/main/resources/application.properties
Labels: enhancement

#87 Group 07 madhushankha desilva
  server/audit-service/.gitattributes
  server/audit-service/.gitignore
  server/audit-service/.mvn/wrapper/maven-wrapper.properties
  server/audit-service/mvnw
  server/audit-service/mvnw.cmd
  server/audit-service/pom.xml
  server/audit-service/src/main/java/com/main/audit_service/AuditServiceApplication.java
  server/audit-service/src/main/resources/application.properties
  server/audit-service/src/test/java/com/main/audit_service/AuditServiceApplicationTests.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/controllers/IPFSController.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/consumer/IPFSListener.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/ipfs/FileServiceImpl.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/ipfs/IPFSService.java
Labels: enhancement

#89 Group 07
  server/audit-service/.gitattributes
  server/audit-service/.gitignore
  server/audit-service/.mvn/wrapper/maven-wrapper.properties
  server/audit-service/mvnw
  server/audit-service/mvnw.cmd
  server/audit-service/pom.xml
  server/audit-service/src/main/java/com/main/audit_service/AuditServiceApplication.java
  server/audit-service/src/main/resources/application.properties
  server/audit-service/src/test/java/com/main/audit_service/AuditServiceApplicationTests.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/controllers/IPFSController.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/consumer/IPFSListener.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/ipfs/FileServiceImpl.java
  server/ipfs-service/src/main/java/com/team07/ipfs_service/services/ipfs/IPFSService.java
Labels: enhancement

#120 IPFS-Service Fully Dockerized
  server/ipfs-service/docker-compose.yml
  server/ipfs-service/dockerfile
  server/ipfs-service/readme.md
  server/ipfs-service/src/main/resources/application.properties
  server/ipfs-service/supervisord.conf
Labels: enhancement, docker

#116 Group 06 harsha dankotuwa
  client/src/app/models/Notification.ts
  client/src/app/pages/doctor/components/footerwidget.ts
  client/src/app/pages/home/components/footerwidget.ts
  client/src/app/pages/patient/components/add-appointmentcomponent.ts
  client/src/app/pages/patient/components/footerwidget.ts
  client/src/app/pages/staff/components/footerwidget.ts
  client/src/app/service/notification.service.ts
  server/api-gateway/Dockerfile
  server/appointment_service/src/main/java/com/team06/appointment_service/config/KafkaProducerConfig.java
  server/appointment_service/src/main/java/com/team06/appointment_service/dto/Notification1Dto.java
  server/appointment_service/src/main/java/com/team06/appointment_service/service/AppointmentService.java
  server/appointment_service/src/main/java/com/team06/appointment_service/service/KafkaProducerService.java
  server/appointment_service/src/main/resources/application.properties
  server/service-auth/Dockerfile
  server/service-auth/src/main/java/com/springboot/healthcare/SpringSecurityApplication.java
  server/service-auth/src/main/java/com/springboot/healthcare/config/KafkaProducerConfig.java
  server/service-auth/src/main/java/com/springboot/healthcare/dto/Notification1Dto.java
  server/service-auth/src/main/java/com/springboot/healthcare/dto/NotificationDto.java
  server/service-auth/src/main/java/com/springboot/healthcare/repo/UserRepo.java
  server/service-auth/src/main/java/com/springboot/healthcare/service/KafkaProducerService.java
Labels: bug fix

#113 debugged and added dockerfile , dockercompose
  server/Microservice-Doctor/springboot-kafka-project/Dockerfile
  server/Microservice-Doctor/springboot-kafka-project/docker-compose.yml
  server/Microservice-Doctor/springboot-kafka-project/src/main/java/DoctorMicroservice/repository/ScheduleSlotRepository.java
  server/Microservice-Doctor/springboot-kafka-project/src/main/java/DoctorMicroservice/service/impl/DoctorSessionServiceImpl.java
Labels: enhancement

#138 Temp dulmini
  .vscode/settings.json
  client/src/app/pages/doctor/doctor.routes.ts
  client/src/app/pages/patient/components/view-appointment.ts
  server/appointment_service/src/main/resources/application.properties
  server/appointment_service/src/test/java/com/team06/appointment_service/AppointmentServiceApplicationTests.java
  server/appointment_service/target/classes/application.properties
  server/appointment_service/target/classes/com/team06/appointment_service/AppointmentServiceApplication.class
  server/appointment_service/target/classes/com/team06/appointment_service/config/KafkaConsumerConfig.class
  server/appointment_service/target/classes/com/team06/appointment_service/config/KafkaProducerConfig.class
  server/appointment_service/target/classes/com/team06/appointment_service/controller/AppointmentController.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/AppointmentBookedDto.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/BookingResponse.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/DoctorKafkaEvent.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/MakeAppointment.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/NotificationDto.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/PatientDto.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/ScheduleSlotDto.class
  server/appointment_service/target/classes/com/team06/appointment_service/dto/SessionIdDto.class
  server/appointment_service/target/classes/com/team06/appointment_service/model/Appointment.class
  server/appointment_service/target/classes/com/team06/appointment_service/model/Availibility.class
  server/appointment_service/target/classes/com/team06/appointment_service/repo/AppointmentRepo.class
  server/appointment_service/target/classes/com/team06/appointment_service/repo/AvailibilityRepo.class
  server/appointment_service/target/classes/com/team06/appointment_service/service/AppointmentService.class
  server/appointment_service/target/classes/com/team06/appointment_service/service/KafkaConsumerService.class
  server/appointment_service/target/classes/com/team06/appointment_service/service/KafkaProducerService.class
  server/appointment_service/target/test-classes/com/team06/appointment_service/AppointmentServiceApplicationTests.class
  server/health-analytics/src/test/java/com/team8/healthanalyticsforadmin/HealthAnalyticsForAdminApplicationTests.java
Labels: enhancement
